package service

var mimeTypeDictionary = map[string]string{
	"text/html":                            "HTML 文档",
	"text/css":                             "CSS 样式表",
	"text/xml":                             "XML 文档",
	"image/gif":                            "GIF 图片",
	"image/jpeg":                           "JPEG 图片",
	"application/javascript":               "JavaScript 脚本",
	"application/atom+xml":                 "Atom XML 源",
	"application/rss+xml":                  "RSS XML 源",
	"text/mathml":                          "MathML 文档",
	"text/plain":                           "普通文本",
	"text/vnd.sun.j2me.app-descriptor":     "J2ME 应用描述",
	"text/vnd.wap.wml":                     "WML 文档",
	"text/x-component":                     "HTML 组件",
	"image/avif":                           "AVIF 图片",
	"image/png":                            "PNG 图片",
	"image/svg+xml":                        "SVG 图片",
	"image/tiff":                           "TIFF 图片",
	"image/vnd.wap.wbmp":                   "WBMP 图片",
	"image/webp":                           "WebP 图片",
	"image/x-icon":                         "ICO 图标",
	"image/x-jng":                          "JNG 图片",
	"image/x-ms-bmp":                       "BMP 图片",
	"font/woff":                            "WOFF 字体",
	"font/woff2":                           "WOFF2 字体",
	"application/java-archive":             "Java 存档",
	"application/json":                     "JSON 数据",
	"application/mac-binhex40":             "Macintosh BinHex 4.0 存档",
	"application/msword":                   "Microsoft Word 文档",
	"application/pdf":                      "Adobe PDF 文档",
	"application/postscript":               "PostScript 文档",
	"application/rtf":                      "Rich Text Format 文档",
	"application/vnd.apple.mpegurl":        "Apple HLS 播放列表",
	"application/vnd.google-earth.kml+xml": "Google Earth KML 文件",
	"application/vnd.google-earth.kmz":     "Google Earth KMZ 存档",
	"application/vnd.ms-excel":             "Microsoft Excel 表格",
	"application/vnd.ms-fontobject":        "MS 字体对象",
	"application/vnd.ms-powerpoint":        "Microsoft PowerPoint 演示文稿",
	"application/vnd.oasis.opendocument.graphics":                               "ODF 图形文档",
	"application/vnd.oasis.opendocument.presentation":                           "ODF 演示文稿",
	"application/vnd.oasis.opendocument.spreadsheet":                            "ODF 电子表格",
	"application/vnd.oasis.opendocument.text":                                   "ODF 文本文档",
	"application/vnd.openxmlformats-officedocument.presentationml.presentation": "PowerPoint 2007+ 演示文稿",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":         "Excel 2007+ 电子表格",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document":   "Word 2007+ 文档",
	"application/vnd.wap.wmlc":                                                  "编译后的 WML 文档",
	"application/wasm":                                                          "WebAssembly 二进制模块",
	"application/x-7z-compressed":                                               "7-Zip 存档",
	"application/x-cocoa":                                                       "Cocoa 应用",
	"application/x-java-archive-diff":                                           "Java 存档差异",
	"application/x-java-jnlp-file":                                              "Java Web 启动文件",
	"application/x-makeself":                                                    "自包含的可执行脚本",
	"application/x-perl":                                                        "Perl 脚本",
	"application/x-pilot":                                                       "PalmPilot 数据",
	"application/x-rar-compressed":                                              "RAR 存档",
	"application/x-redhat-package-manager":                                      "Red Hat 软件包管理器包",
	"application/x-sea":                                                         "SEA 存档",
	"application/x-shockwave-flash":                                             "Adobe Flash 动画",
	"application/x-stuffit":                                                     "StuffIt 存档",
	"application/x-tcl":                                                         "Tcl 脚本",
	"application/x-x509-ca-cert":                                                "X.509 证书",
	"application/x-xpinstall":                                                   "Mozilla 安装脚本",
	"application/xhtml+xml":                                                     "XHTML 文档",
	"application/xspf+xml":                                                      "XSPF 播放列表",
	"application/zip":                                                           "ZIP 存档",
	"application/octet-stream":                                                  "二进制数据流",
	"audio/midi":                                                                "MIDI 音频",
	"audio/mpeg":                                                                "MP3 音频",
	"audio/ogg":                                                                 "Ogg 音频",
	"audio/x-m4a":                                                               "M4A 音频",
	"audio/x-realaudio":                                                         "RealAudio 音频",
	"video/3gpp":                                                                "3GPP 视频",
	"video/mp2t":                                                                "MPEG-2 传输流",
	"video/mp4":                                                                 "MP4 视频",
	"video/mpeg":                                                                "MPEG 视频",
	"video/quicktime":                                                           "QuickTime 视频",
	"video/webm":                                                                "WebM 视频",
	"video/x-flv":                                                               "FLV 视频",
	"video/x-m4v":                                                               "M4V 视频",
	"video/x-mng":                                                               "MNG 视频",
	"video/x-ms-asf":                                                            "Microsoft ASF 视频",
	"video/x-ms-wmv":                                                            "Windows Media Video",
	"video/x-msvideo":                                                           "AVI 视频",
}

var fileExtNameDictionary = map[string]string{
	"html":    "text/html",
	"htm":     "text/html",
	"shtml":   "text/html",
	"css":     "text/css",
	"xml":     "text/xml",
	"gif":     "image/gif",
	"jpeg":    "image/jpeg",
	"jpg":     "image/jpeg",
	"js":      "application/javascript",
	"atom":    "application/atom+xml",
	"rss":     "application/rss+xml",
	"mml":     "text/mathml",
	"txt":     "text/plain",
	"jad":     "text/vnd.sun.j2me.app-descriptor",
	"wml":     "text/vnd.wap.wml",
	"htc":     "text/x-component",
	"avif":    "image/avif",
	"png":     "image/png",
	"svg":     "image/svg+xml",
	"svgz":    "image/svg+xml",
	"tif":     "image/tiff",
	"tiff":    "image/tiff",
	"wbmp":    "image/vnd.wap.wbmp",
	"webp":    "image/webp",
	"ico":     "image/x-icon",
	"jng":     "image/x-jng",
	"bmp":     "image/x-ms-bmp",
	"woff":    "font/woff",
	"woff2":   "font/woff2",
	"jar":     "application/java-archive",
	"war":     "application/java-archive",
	"ear":     "application/java-archive",
	"json":    "application/json",
	"hqx":     "application/mac-binhex40",
	"doc":     "application/msword",
	"pdf":     "application/pdf",
	"ps":      "application/postscript",
	"eps":     "application/postscript",
	"ai":      "application/postscript",
	"rtf":     "application/rtf",
	"m3u8":    "application/vnd.apple.mpegurl",
	"kml":     "application/vnd.google-earth.kml+xml",
	"kmz":     "application/vnd.google-earth.kmz",
	"xls":     "application/vnd.ms-excel",
	"eot":     "application/vnd.ms-fontobject",
	"ppt":     "application/vnd.ms-powerpoint",
	"odg":     "application/vnd.oasis.opendocument.graphics",
	"odp":     "application/vnd.oasis.opendocument.presentation",
	"ods":     "application/vnd.oasis.opendocument.spreadsheet",
	"odt":     "application/vnd.oasis.opendocument.text",
	"pptx":    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	"xlsx":    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"docx":    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"wmlc":    "application/vnd.wap.wmlc",
	"wasm":    "application/wasm",
	"7z":      "application/x-7z-compressed",
	"cco":     "application/x-cocoa",
	"jardiff": "application/x-java-archive-diff",
	"jnlp":    "application/x-java-jnlp-file",
	"run":     "application/x-makeself",
	"pl":      "application/x-perl",
	"pm":      "application/x-perl",
	"prc":     "application/x-pilot",
	"pdb":     "application/x-pilot",
	"rar":     "application/x-rar-compressed",
	"rpm":     "application/x-redhat-package-manager",
	"sea":     "application/x-sea",
	"swf":     "application/x-shockwave-flash",
	"sit":     "application/x-stuffit",
	"tcl":     "application/x-tcl",
	"tk":      "application/x-tcl",
	"der":     "application/x-x509-ca-cert",
	"pem":     "application/x-x509-ca-cert",
	"crt":     "application/x-x509-ca-cert",
	"xpi":     "application/x-xpinstall",
	"xhtml":   "application/xhtml+xml",
	"xspf":    "application/xspf+xml",
	"zip":     "application/zip",
	"bin":     "application/octet-stream",
	"exe":     "application/octet-stream",
	"dll":     "application/octet-stream",
	"deb":     "application/octet-stream",
	"dmg":     "application/octet-stream",
	"iso":     "application/octet-stream",
	"img":     "application/octet-stream",
	"msi":     "application/octet-stream",
	"msp":     "application/octet-stream",
	"msm":     "application/octet-stream",
	"mid":     "audio/midi",
	"midi":    "audio/midi",
	"kar":     "audio/midi",
	"mp3":     "audio/mpeg",
	"ogg":     "audio/ogg",
	"m4a":     "audio/x-m4a",
	"ra":      "audio/x-realaudio",
	"3gpp":    "video/3gpp",
	"3gp":     "video/3gpp",
	"ts":      "video/mp2t",
	"mp4":     "video/mp4",
	"mpeg":    "video/mpeg",
	"mpg":     "video/mpeg",
	"mov":     "video/quicktime",
	"webm":    "video/webm",
	"flv":     "video/x-flv",
	"m4v":     "video/x-m4v",
	"mng":     "video/x-mng",
	"asx":     "video/x-ms-asf",
	"asf":     "video/x-ms-asf",
	"wmv":     "video/x-ms-wmv",
	"avi":     "video/x-msvideo",
}
